### ISSUE TITLE
[ARTesla] UnsatisfiedLinkError  couldn't find libgvr.so

### ISSUE THREAD

**Issue by adamchojnacki** [viromedia/virocore#114]
Hello,

I am trying to execute ARTesla example on AVD simulator (Pixel 2 with ARCore 1.1 installed) but I am getting following error (while starting the application) 

`05-09 13:16:14.082 5004-5004/com.example.virosample.arcore E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.virosample.arcore, PID: 5004
    java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.example.virosample.arcore-PdjNwc9GZ_Q5GvYpGb2uZQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.example.virosample.arcore-PdjNwc9GZ_Q5GvYpGb2uZQ==/lib/x86, /data/app/com.example.virosample.arcore-PdjNwc9GZ_Q5GvYpGb2uZQ==/base.apk!/lib/x86, /system/lib, /vendor/lib]]] couldn't find "libgvr.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1011)
        at java.lang.System.loadLibrary(System.java:1657)
        at com.viro.core.ViroViewARCore.init(ViroViewARCore.java:388)
        at com.viro.core.ViroViewARCore.<init>(ViroViewARCore.java:338)
        at com.viro.core.ViroViewARCore.<init>(ViroViewARCore.java:310)
        at com.example.virosample.ViroActivityAR.onCreate(ViroActivityAR.java:98)
        at android.app.Activity.performCreate(Activity.java:6975)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1213)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2770)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6541)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)`

As I understand libgvr.so is not in /lib/x86 - what am I missing here (I need to install some additional component) ?

**Comment by dam00n** [comment]
Viro does not currently support Android emulator. You need to use a device for AR/VR development. Let us know if you have issues when using a device.

**Comment by adamchojnacki** [comment]
Hi,
thanks for the reply.
Since there are issues regarding Android emulator support [https://github.com/viromedia/virocore/issues/66](url) and [https://github.com/viromedia/virocore/issues/57](url) I think we can close this issue.

Just a thought - maybe it is worth to mention on [https://virocore.viromedia.com/docs/getting-started]url  that Android emulator support is not ready yet.
