### ISSUE TITLE
black screen on Xiaomi Mi Mix 2S?

### ISSUE THREAD

**Issue by scolar** [viromedia/virocore#154]
i use virocore 1.7.2,while loading more than 10 obj models in the scene,the screen become black.

**Comment by dthian** [comment]
Hey @scolar, apologies for the late reply, is it possible to:
1) grab the logs on the device when the screen goes black? 
2) Provide us the model you are trying to load?

From the above, I suspect that it may be a memory issue where we may be loading numerous memory intensive models into the scene. Much thanks!

**Comment by dam00n** [comment]
Can you upgrade to ViroCore 1.9 and let us know if you are still seeing this issue?

**Comment by panicg** [comment]
s8 in use


I have the same symptoms.

**Comment by MartinRGB** [comment]
## Erro Log

08-24 20:26:19.472 3530-3530/com.example.virosample I/Viro: Error: Unknown error when installing ARCore
    com.google.ar.core.exceptions.UnavailableDeviceNotCompatibleException
        at com.google.ar.core.Session.throwExceptionFromArStatus(Unknown Source:144)
        at com.google.ar.core.Session.nativeCreateSession(Native Method)
        at com.google.ar.core.Session.<init>(Unknown Source:22)
        at com.viro.core.ViroViewARCore.requestARCoreInstall(ViroViewARCore.java:503)
        at com.viro.core.ViroViewARCore.onActivityResumed(ViroViewARCore.java:708)
        at com.example.virosample.ProductARActivity.onResume(ProductARActivity.java:151)
        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1356)
        at android.app.Activity.performResume(Activity.java:7459)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3810)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3886)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1822)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:200)
        at android.app.ActivityThread.main(ActivityThread.java:7038)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:519)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:837)

**08-24 20:26:19.472 3530-3530/com.example.virosample E/ProductARActivity: Failed to load AR Scene [This device does not support AR]**

## Device
- Xiaomi 6
- OPPO Find X

...

**Comment by dam00n** [comment]
@MartinRGB are you seeing issues on the Xiaomi Mi Mix S2 or on Xiaomi 6 and Oppo Find X?

If the latter, those devices are not support by ARCore at this time. We use ARCore for tracking and therefore are limited by their device support. Here is a list of supported devices -> https://developers.google.com/ar/discover/supported-devices

**Comment by MartinRGB** [comment]
@dam00n Thx for your reply
