### ISSUE TITLE
Class name (com/google/ar/core/B) does not match path (com/google/ar/core/b.class)

### ISSUE THREAD

**Issue by variux** [viromedia/virocore#162]
Today I try to compile the project ARRetail and when I try to do it, I get this error, often it says 
`class name (com/google/ar/core/A) does not match path (com/google/ar/core/A.class)`

I'm using Mac OS X
Android Studio 3.1.0
Gradle 3.0.1

When I open the project Android Studio start signing and making updates to the project but I don't know if this is affecting 

This is my build.gradle file (Module app) (In theory I didn't modify anything)
`apply plugin: 'com.android.application'

android {
    compileSdkVersion 25
    buildToolsVersion "26.0.1"
    defaultConfig {
        applicationId "com.example.virosample"
        minSdkVersion 21
        targetSdkVersion 25
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
        ndk {
            abiFilters "armeabi-v7a", "x86", "armeabi", "mips"
        }
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'com.android.support:recyclerview-v7:25.0.0'
    compile 'com.android.support:appcompat-v7:25.0.0'
    compile 'com.google.android.exoplayer:exoplayer:2.7.1'
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    compile 'com.android.support.constraint:constraint-layout:1.0.2'
    testCompile 'junit:junit:4.12'
    compile project(':gvr_common')
    compile project(':arcore_client')
    compile project(':viro_core')
    compile 'com.google.protobuf.nano:protobuf-javanano:3.0.0-alpha-7'
    compile 'com.amazonaws:aws-android-sdk-core:2.2.+'
    compile 'com.amazonaws:aws-android-sdk-ddb:2.2.+'
    compile 'com.amazonaws:aws-android-sdk-ddb-mapper:2.2.+'
    compile 'com.amazonaws:aws-android-sdk-cognito:2.2.+'
    compile 'com.amazonaws:aws-android-sdk-cognitoidentityprovider:2.2.+'
}
`
This is the log 

`07-11 20:17:47.955 14658-14658/com.example.virosample E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.virosample, PID: 14658
    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/ar/core/a;
        at com.google.ar.core.ArCoreApk$Availability.<clinit>(Unknown Source)
        at com.google.ar.core.B.a(Unknown Source)
        at com.google.ar.core.h.checkAvailability(Unknown Source)
        at com.viro.core.ViroViewARCore.isDeviceCompatible(ViroViewARCore.java:918)
        at com.viro.core.ViroViewARCore.init(ViroViewARCore.java:382)
        at com.viro.core.ViroViewARCore.<init>(ViroViewARCore.java:341)
        at com.example.virosample.ProductARActivity.onCreate(ProductARActivity.java:119)
        at android.app.Activity.performCreate(Activity.java:6912)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1126)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2877)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2985)
        at android.app.ActivityThread.-wrap14(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1635)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6692)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.ar.core.a" on path: DexPathList[[zip file "/data/app/com.example.virosample-1/base.apk", zip file "/data/app/com.example.virosample-1/split_lib_dependencies_apk.apk", zip file "/data/app/com.example.virosample-1/split_lib_slice_0_apk.apk", zip file "/data/app/com.example.virosample-1/split_lib_slice_1_apk.apk", zip file "/data/app/com.example.virosample-1/split_lib_slice_2_apk.apk", zip file "/data/app/com.example.virosample-1/split_lib_slice_3_apk.apk", zip file "/data/app/com.example.virosample-1/split_lib_slice_4_apk.apk", zip file "/data/app/com.example.virosample-1/split_lib_slice_5_apk.apk", zip file "/data/app/com.example.virosample-1/split_lib_slice_6_apk.apk", zip file "/data/app/com.example.virosample-1/split_lib_slice_7_apk.apk", zip file "/data/app/com.example.virosample-1/split_lib_slice_8_apk.apk", zip file "/data/app/com.example.virosample-1/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.example.virosample-1/lib/arm, /data/app/com.example.virosample-1/base.apk!/lib/armeabi-v7a, /data/app/com.example.virosample-1/split_lib_dependencies_apk.apk!/lib/armeabi-v7a, /data/app/com.example.virosample-1/split_lib_slice_0_apk.apk!/lib/armeabi-v7a, /data/app/com.example.virosample-1/split_lib_slice_1_apk.apk!/lib/armeabi-v7a, /data/app/com.example.virosample-1/split_lib_slice_2_apk.apk!/lib/armeabi-v7a, /data/app/com.example.virosample-1/split_lib_slice_3_apk.apk!/lib/armeabi-v7a, /data/app/com.example.virosample-1/split_lib_slice_4_apk.apk!/lib/armeabi-v7a, /data/app/com.example.virosample-1/split_lib_slice_5_apk.apk!/lib/armeabi-v7a, /data/app/com.example.virosample-1/split_lib_slice_6_apk.apk!/lib/armeabi-v7a, /data/app/com.example.virosample-1/split_lib_slice_7_apk.apk!/lib/armeabi-v7a, /data/app/com.example.virosample-1/split_lib_slice_8_apk.apk!/lib/armeabi-v7a, /data/app/com.example.virosample-1/split_lib_slice_9_apk.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.google.ar.core.ArCoreApk$Availability.<clinit>(Unknown Source) 
        at com.google.ar.core.B.a(Unknown Source) 
        at com.google.ar.core.h.checkAvailability(Unknown Source) 
        at com.viro.core.ViroViewARCore.isDeviceCompatible(ViroViewARCore.java:918) 
        at com.viro.core.ViroViewARCore.init(ViroViewARCore.java:382) 
        at com.viro.core.ViroViewARCore.<init>(ViroViewARCore.java:341) 
        at com.example.virosample.ProductARActivity.onCreate(ProductARActivity.java:119) 
        at android.app.Activity.performCreate(Activity.java:6912) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1126) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2877) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2985) 
        at android.app.ActivityThread.-wrap14(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1635) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6692) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358) `
Thank you.

**Comment by dthian** [comment]
Hey @variux, how were you able to resolve the issue above?

**Comment by variux** [comment]
Hi @dthian I didn't read the steps carefully mainly in the part of deactivate instant run, downloading again the project and deactivating instant run solves the problem
