### ISSUE TITLE
UnsatisfiedLinkError

### ISSUE THREAD

**Issue by gokulsukumar03** [viromedia/virocore#217]
2018-10-24 09:46:25.211 11865-11865/com.example.virosample E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.virosample, PID: 11865
    java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.example.virosample-uV9GFP2D-hZHyfSFN1TRXQ==/base.apk", zip file "/data/app/com.example.virosample-uV9GFP2D-hZHyfSFN1TRXQ==/split_lib_dependencies_apk.apk", zip file "/data/app/com.example.virosample-uV9GFP2D-hZHyfSFN1TRXQ==/split_lib_resources_apk.apk", zip file "/data/app/com.example.virosample-uV9GFP2D-hZHyfSFN1TRXQ==/split_lib_slice_0_apk.apk", zip file "/data/app/com.example.virosample-uV9GFP2D-hZHyfSFN1TRXQ==/split_lib_slice_1_apk.apk", zip file "/data/app/com.example.virosample-uV9GFP2D-hZHyfSFN1TRXQ==/split_lib_slice_2_apk.apk", zip file "/data/app/com.example.virosample-uV9GFP2D-hZHyfSFN1TRXQ==/split_lib_slice_3_apk.apk", zip file "/data/app/com.example.virosample-uV9GFP2D-hZHyfSFN1TRXQ==/split_lib_slice_4_apk.apk", zip file "/data/app/com.example.virosample-uV9GFP2D-hZHyfSFN1TRXQ==/split_lib_slice_5_apk.apk", zip file "/data/app/com.example.virosample-uV9GFP2D-hZHyfSFN1TRXQ==/split_lib_slice_6_apk.apk", zip file "/data/app/com.example.virosample-uV9GFP2D-hZHyfSFN1TRXQ==/split_lib_slice_7_apk.apk", zip file "/data/app/com.example.virosample-uV9GFP2D-hZHyfSFN1TRXQ==/split_lib_slice_8_apk.apk", zip file "/data/app/com.example.virosample-uV9GFP2D-hZHyfSFN1TRXQ==/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.example.virosample-uV9GFP2D-hZHyfSFN1TRXQ==/lib/x86, /data/app/com.example.virosample-uV9GFP2D-hZHyfSFN1TRXQ==/base.apk!/lib/x86, /data/app/com.example.virosample-uV9GFP2D-hZHyfSFN1TRXQ==/split_lib_dependencies_apk.apk!/lib/x86, /data/app/com.example.virosample-uV9GFP2D-hZHyfSFN1TRXQ==/split_lib_resources_apk.apk!/lib/x86, /data/app/com.example.virosample-uV9GFP2D-hZHyfSFN1TRXQ==/split_lib_slice_0_apk.apk!/lib/x86, /data/app/com.example.virosample-uV9GFP2D-hZHyfSFN1TRXQ==/split_lib_slice_1_apk.apk!/lib/x86, /data/app/com.example.virosample-uV9GFP2D-hZHyfSFN1TRXQ==/split_lib_slice_2_apk.apk!/lib/x86, /data/app/com.example.virosample-uV9GFP2D-hZHyfSFN1TRXQ==/split_lib_slice_3_apk.apk!/lib/x86, /data/app/com.example.virosample-uV9GFP2D-hZHyfSFN1TRXQ==/split_lib_slice_4_apk.apk!/lib/x86, /data/app/com.example.virosample-uV9GFP2D-hZHyfSFN1TRXQ==/split_lib_slice_5_apk.apk!/lib/x86, /data/app/com.example.virosample-uV9GFP2D-hZHyfSFN1TRXQ==/split_lib_slice_6_apk.apk!/lib/x86, /data/app/com.example.virosample-uV9GFP2D-hZHyfSFN1TRXQ==/split_lib_slice_7_apk.apk!/lib/x86, /data/app/com.example.virosample-uV9GFP2D-hZHyfSFN1TRXQ==/split_lib_slice_8_apk.apk!/lib/x86, /data/app/com.example.virosample-uV9GFP2D-hZHyfSFN1TRXQ==/split_lib_slice_9_apk.apk!/lib/x86, /system/lib, /vendor/lib]]] couldn't find "libgvr.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1011)
        at java.lang.System.loadLibrary(System.java:1657)
        at com.viro.core.ViroViewARCore.<clinit>(ViroViewARCore.java:75)
        at com.example.virosample.ViroActivity.onCreate(ViroActivity.java:75)
        at android.app.Activity.performCreate(Activity.java:7009)
        at android.app.Activity.performCreate(Activity.java:7000)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**Comment by dam00n** [comment]
Can you fill out the info requested in the Github form so we can better understand your issue and diagnose?


  - [ ] Review the documentation: https://virocore.viromedia.com/
  - [ ] Search for existing issues: https://github.com/viromedia/virocore/issues
  - [ ] Use the latest ViroCore release: https://virocore.viromedia.com/docs/releases
  - [ ] Turn off Instant Run in Android Studio

## Environment
Please provide the following information about your environment:
1. OS: Mac, Windows, Linux
2. Version: ViroCore version 
3. Device(s): What device(s) are you are seeing the issue on (i.e. Samsung Note 8, Pixel 2 XL, etc)

## Description
Describe your issue in detail. Include screenshots if needed. If this is a regression, let us know.

## Reproducible Demo
Let us know how to reproduce the issue. Include a code sample, screen capture, video recording. The more information you provide, the better we can support you.
