### ISSUE TITLE
Examples crash with "java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "__aeabi_memclr8""

### ISSUE THREAD

**Issue by fanshtorm** [viromedia/virocore#302]
## Environment
1. OS: Windows
2. Version: latest
3. Device: Samsung Galaxy A5 (SM-A500FU) Android 6.0.1 (firmware version: A500FUXXU1CPI2)

## Description
The sample apps, for example ARBlackPanther, crash at start of the execution in line 74 in ViroActivityAR.java in ARBlackPanther app
`10558-10558/? E/Zygote: v2
10558-10558/com.example.virosample.arcore E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.virosample.arcore, PID: 10558
    java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "__aeabi_memclr8" referenced by "/data/app/com.example.virosample.arcore-2/lib/arm/libviro_arcore.so"...
        at java.lang.Runtime.loadLibrary(Runtime.java:372)
        at java.lang.System.loadLibrary(System.java:1076)
        at com.viro.core.ViroViewARCore.init(ViroViewARCore.java:491)
        at com.viro.core.ViroViewARCore.<init>(ViroViewARCore.java:446)
        at com.viro.core.ViroViewARCore.<init>(ViroViewARCore.java:418)
        at com.example.virosample.ViroActivityAR.onCreate(ViroActivityAR.java:74)
        at android.app.Activity.performCreate(Activity.java:6904)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1136)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3266)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3415)
        at android.app.ActivityThread.access$1100(ActivityThread.java:229)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1821)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:7331)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
`

## Reproducible Demo
To reproduce it just run examples on such device

**Comment by ktemby** [comment]
I ran across the same issue on a Samsung S5 (even older).  The A5 should be able to run AR core.  The S5 at least is at the minimumSDK version (23) but that doesn't seem to matter.  Did you follow the integration instructions here: https://docs.viromedia.com/docs/integrating-with-react-native-projects . 

Here's the supported android device list btw: https://developers.google.com/ar/discover/supported-devices#android_play

**Comment by gblue1223** [comment]
Same issue on Samsung S5. @ktemby, did you solve the problem?
