### ISSUE TITLE
Getting exception  Caused by: com.google.ar.core.exceptions.UnavailableArcoreNotInstalledException

### ISSUE THREAD

**Issue by deshmukhrohit11** [viromedia/virocore#34]
Hi, I am trying to run sample code from "ARRetail". But, I am getting the following exception.
I am using Google Pixel and also installed Arcore-preview.apk. 

02-28 04:35:42.480 12594-12594/com.example.virosample.arcore E/AndroidRuntime: FATAL EXCEPTION: main
                                                                               Process: com.example.virosample.arcore, PID: 12594
                                                                               java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.virosample.arcore/com.example.virosample.ProductARActivityComplete}: com.google.ar.core.exceptions.UnavailableArcoreNotInstalledException
                                                                                   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2778)
                                                                                   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
                                                                                   at android.app.ActivityThread.-wrap11(Unknown Source:0)
                                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                   at android.os.Looper.loop(Looper.java:164)
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:6494)
                                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                                   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
                                                                                Caused by: com.google.ar.core.exceptions.UnavailableArcoreNotInstalledException
                                                                                   at com.google.ar.core.Session.throwExceptionFromArStatus(Session.java:343)
                                                                                   at com.google.ar.core.Session.nativeCreateSession(Native Method)
                                                                                   at com.google.ar.core.Session.<init>(Session.java:87)
                                                                                   at com.viro.core.ViroViewARCore.init(ViroViewARCore.java:239)
                                                                                   at com.viro.core.ViroViewARCore.<init>(ViroViewARCore.java:192)
                                                                                   at com.example.virosample.ViroActivity.onCreate(ViroActivity.java:58)
                                                                                   at com.example.virosample.ProductARActivityComplete.onCreate(ProductARActivityComplete.java:91)
                                                                                   at android.app.Activity.performCreate(Activity.java:6999)
                                                                                   at android.app.Activity.performCreate(Activity.java:6990)
                                                                                   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)

Thank you in advance.

**Comment by dam00n** [comment]
Hi @deshmukhrohit11 can you check that your viro version and arcore version match?

ViroCore 1.3 (pre 2/26) works with ARCore Dev Preview 2 apk 

ViroCore 1.4 (release 2/26) works with ARCore 1.0 apk which is available in the Google Play store.

**Comment by PaulohFerreira** [comment]
Maybe this is an ARCore problem? I ran into this same problem using the ViroCore 1.4 and the ARCore 1.0, but I found this [ARCore issue](https://github.com/google-ar/arcore-android-sdk/issues/130) when looking for more informations. I just disabeled the Instant Run in the project, and after this the code ran smoothly. Hope this help in any way.

**Comment by dam00n** [comment]
Thanks @PaulohFerreira for adding this suggestion. Forgot to note that turning off instant run might help. The last comment on the ARCore Github Issue re: Instant Run is actually from the Viro team :)

**Comment by dam00n** [comment]
Closing issue as answer provided and arcore-preview is no longer being used.
