### ISSUE TITLE
App crashes on devices with ABI arm64-v8a throws Error: java.lang.UnsatisfiedLinkError

### ISSUE THREAD

**Issue by ssaxena0891** [viromedia/virocore#43]
It throws java.lang.UnsatisfiedLinkError when I try to load a 3D model using an OBJ file. Below is my stacktrace:

java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.example-2/base.apk", zip file "/data/app/com.example-2/split_lib_dependencies_apk.apk", zip file "/data/app/com.example-2/split_lib_slice_0_apk.apk", zip file "/data/app/com.example-2/split_lib_slice_1_apk.apk", zip file "/data/app/com.example-2/split_lib_slice_2_apk.apk", zip file "/data/app/com.example-2/split_lib_slice_3_apk.apk", zip file "/data/app/com.example-2/split_lib_slice_4_apk.apk", zip file "/data/app/com.example-2/split_lib_slice_5_apk.apk", zip file "/data/app/com.example-2/split_lib_slice_6_apk.apk", zip file "/data/app/com.example-2/split_lib_slice_7_apk.apk", zip file "/data/app/com.example-2/split_lib_slice_8_apk.apk", zip file "/data/app/com.example-2/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.example-2/lib/arm64, /data/app/com.example-2/base.apk!/lib/arm64-v8a, /data/app/com.example-2/split_lib_dependencies_apk.apk!/lib/arm64-v8a, /data/app/com.example-2/split_lib_slice_0_apk.apk!/lib/arm64-v8a, /data/app/com.example-2/split_lib_slice_1_apk.apk!/lib/arm64-v8a, /data/app/com.example-2/split_lib_slice_2_apk.apk!/lib/arm64-v8a, /data/app/com.example-2/split_lib_slice_3_apk.apk!/lib/arm64-v8a, /data/app/com.example-2/split_lib_slice_4_apk.apk!/lib/arm64-v8a, /data/app/com.example-2/split_lib_slice_5_apk.apk!/lib/arm64-v8a, /data/app/com.example-2/split_lib_slice_6_apk.apk!/lib/arm64-v8a, /data/app/com.example-2/split_lib_slice_7_apk.apk!/lib/arm64-v8a, /data/app/com.example-2/split_lib_slice_8_apk.apk!/lib/arm64-v8a, /data/app/com.example-2/split_lib_slice_9_apk.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]] couldn't find "libgvr.so"
                                                                      at java.lang.Runtime.loadLibrary0(Runtime.java:972)
                                                                      at java.lang.System.loadLibrary(System.java:1567)
                                                                      at com.viro.core.ViroViewScene.<clinit>(ViroViewScene.java:50)
                                                                      at java.lang.reflect.Constructor.newInstance0(Native Method)
                                                                      at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
                                                                      at android.view.LayoutInflater.createView(LayoutInflater.java:652)
                                                                      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:794)
                                                                      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:734)
                                                                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:865)
                                                                      at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:828)
                                                                      at android.view.LayoutInflater.inflate(LayoutInflater.java:525)
                                                                      at android.view.LayoutInflater.inflate(LayoutInflater.java:427)
                                                                      at android.view.LayoutInflater.inflate(LayoutInflater.java:378)
                                                                      at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287)
                                                                      at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139)
                                                                      at com.example.model3d.virocore.ViroActivity.onCreate(ViroActivity.java:106)
                                                                      at android.app.Activity.performCreate(Activity.java:6912)
                                                                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1126)
                                                                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2900)
                                                                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3008)
                                                                      at android.app.ActivityThread.-wrap14(ActivityThread.java)
                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650)
                                                                      at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                      at android.os.Looper.loop(Looper.java:154)
                                                                      at android.app.ActivityThread.main(ActivityThread.java:6688)
                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)

**Comment by radvani** [comment]
Hi @ssaxena0891, I'm looking into this now. Could you let me know what device you're using so we can test that one out specifically? We're going to launch with more architectures soon.

**Comment by ssaxena0891** [comment]
Hi @radvani, I got this crash on Samsung galaxy s7.

**Comment by radvani** [comment]
Hi @ssaxena0891, it may that you're using another library as well that does include arm64-v8a symbols, causing your app as a whole to search for those symbols in all libraries. You can force your app to just look for armeabi-v7a symbols by adding the following line to your app's build.gradle under ```defaultConfig``` in the ```android``` section:
```
ndk {
        abiFilters "armeabi-v7a", "x86", "armeabi", "mips"
    }
```

So your build.gradle would look something like this:
```
android {
    ...
    defaultConfig {
        ...

        ndk {
            // Specifies the ABI configurations of your native
            // libraries Gradle should build and package with your APK.
            abiFilters 'armeabi-v7a'
        }
    }
```
Let me know if that works for you.

**Comment by ssaxena0891** [comment]
Hi @radvani, with the above code now the app doesn't crash but my mode doesn't load. However I am receiving onObject3DLoaded callback successfully.

**Comment by radvani** [comment]
Hi @ssaxena0891, a few things to verify about your model:

1. Is it positioned and scaled correctly? The bounding box of the model is printed out in the logs.
2. Is there a light in your scene? Without a light, the model will not show up as there is nothing to illuminate it.

**Comment by ssaxena0891** [comment]
@radvani, yes the position, scaling and lighting is correct and also it is working fine on devices with ABIs other than 'arm64-v8a'.

**Comment by radvani** [comment]
Hi @ssaxena0891, if you are able to could you send us the model you're using so we can try it out on our own arm64-v8a devices? We'd like to be able to reproduce this bug. Our email is support@viromedia.com. Thanks!

**Comment by ssaxena0891** [comment]
Hi @radvani, I have uploaded the complete code here https://drive.google.com/file/d/1Y5DSCvpCJRpaERIcLhFe55iZSdqKItKV/view?usp=sharing.

In the code you can see I am trying to load an OBJ file. Following are the screenshots of the results I get when run on two devices:

**On Moto C Plus (Everything working fine):** 
![device-moto_c_plus](https://user-images.githubusercontent.com/16716439/38022280-b56bd55a-329c-11e8-8cc1-b2e9881ca31c.png)

**On Samsung galaxy S7 (getting a black screen):**
![device-samsung_galaxy_s7](https://user-images.githubusercontent.com/16716439/38022332-d41d02b2-329c-11e8-9dfa-7d68aed4f2f3.png)

**Comment by radvani** [comment]
Hi @ssaxena0891, 

I managed to get your model to appear on an S7 and a Pixel. There were two small errors:

In the MTL file associated with your OBJ, there was a reference to a texture called 'ship.jpg' which did not exist. This caused an Exception preventing the model from loading. I modified the MTL file so that it instead refers to 'truck.jpg', which does exist.

The AmbientLight you're using should have a higher intensity. Intensity values range from 0 to 1000, so you'll probably want that intensity set to 1000. (Note this range is because when using physically based rendering, intensity is specified in Lumens).

Finally, our next release will print out more verbose errors when loading models so you'll be able to discover the missing texture issue more easily.

I've attached the revised MTL file.
[truck.mtl.zip](https://github.com/viromedia/virocore/files/1856469/truck.mtl.zip)

**Comment by ssaxena0891** [comment]
Thanks @radvani, setting the intensity to 1000 works. However I am still wondering why the same intensity value had difference in the resulted intensity on those two devices.

Thanks again for the help.

**Comment by radvani** [comment]
Hi @ssaxena0891, I'm not sure it was the light intensity that was reacting differently between the two devices, it may have been the way the two devices responded to the error condition (the mis-named texture).
