### ISSUE TITLE
ViroCore 1.5.0 - getting UnsatisfiedLinkError

### ISSUE THREAD

**Issue by jacobwyn** [viromedia/virocore#65]
Hi guys, I have updated to 1.5.0 and cannot launch my app
Device - google pixel 2, Android 8.1
```
04-02 11:09:54.006 11009-11009 I/zygote64: Late-enabling -Xcheck:jni
04-02 11:09:54.070 11009-11024 D/libEGL: loaded /vendor/lib64/egl/libEGL_adreno.so
04-02 11:09:54.076 11009-11024 D/libEGL: loaded /vendor/lib64/egl/libGLESv1_CM_adreno.so
04-02 11:09:54.076 11009-11009 W/zygote64: Class android.support.v4.util.SimpleArrayMap failed lock verification and will run slower.
04-02 11:09:54.076 11009-11009 W/zygote64: Common causes for lock verification issues are non-optimized dex code
04-02 11:09:54.076 11009-11009 W/zygote64: and incorrect proguard optimizations.
04-02 11:09:54.087 11009-11024 D/libEGL: loaded /vendor/lib64/egl/libGLESv2_adreno.so
04-02 11:09:54.104 11009-11009 W/zygote64: Class com.amazonaws.util.VersionInfoUtils failed lock verification and will run slower.
04-02 11:09:54.123 11009-11009 I/AmazonWebServiceClient: {cognito-identity, us-west-2} was not found in region metadata, trying to construct an endpoint using the standard pattern for this region: 'cognito-identity.us-west-2.amazonaws.com'.
04-02 11:09:54.129 11009-11009 D/CognitoCachingCredentialsProvider: Loading credentials from SharedPreferences
04-02 11:09:54.145 11009-11009 I/Viro: ARCore availability check returned [SUPPORTED_INSTALLED]
04-02 11:09:54.144 11009-11009 W/com.loopme.ar: type=1400 audit(0.0:24084): avc: denied { read } for name="stat" dev="proc" ino=4026532079 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:proc_stat:s0 tclass=file permissive=0
04-02 11:09:54.151 11009-11009 D/AndroidRuntime: Shutting down VM
04-02 11:09:54.152 11009-11009 E/AndroidRuntime: FATAL EXCEPTION: main
                                                 Process: com.loopme.ar, PID: 11009
                                                 java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.loopme.ar-AUOUR-RuL6NZCI5271MJNg==/base.apk"],nativeLibraryDirectories=[/data/app/com.loopme.ar-AUOUR-RuL6NZCI5271MJNg==/lib/arm64, /data/app/com.loopme.ar-AUOUR-RuL6NZCI5271MJNg==/base.apk!/lib/arm64-v8a, /system/lib64]]] couldn't find "libviro_native.so"
                                                     at java.lang.Runtime.loadLibrary0(Runtime.java:1011)
                                                     at java.lang.System.loadLibrary(System.java:1657)
                                                     at com.viro.core.ViroViewARCore.init(ViroViewARCore.java:378)
                                                     at com.viro.core.ViroViewARCore.<init>(ViroViewARCore.java:326)
                                                     at com.loopme.ar.ViroBaseActivity.onCreate(ViroBaseActivity.java:48)
                                                     at com.loopme.ar.AdActivity.onCreate(AdActivity.java:48)
                                                     at android.app.Activity.performCreate(Activity.java:6999)
                                                     at android.app.Activity.performCreate(Activity.java:6990)
                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
                                                     at android.app.ActivityThread.-wrap11(Unknown Source:0)
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
                                                     at android.os.Handler.dispatchMessage(Handler.java:106)
                                                     at android.os.Looper.loop(Looper.java:164)
                                                     at android.app.ActivityThread.main(ActivityThread.java:6494)
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```
in build.gradle
```
android {
  ...
  splits {
    abi {
      enable true
      reset()

      // Specifies a list of ABIs that Gradle should create APKs for
      include "armeabi-v7a", "arm64-v8a"

      // Specifies that we do not want to also generate a universal APK that includes all ABIs
      universalApk false
    }
  }
}
```

**Comment by jacobwyn** [comment]
Sorry guys, the problem was on my side.... anyway thanks for the help)

**Comment by dhruvesh13** [comment]
Can  you put up the solution please
